
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jul 12 2025 15:50:50 CEST (Jul 12 2025 13:50:50 UTC)

// Verification Directory fv/pld 

module pld(inputs_i, and_matrix_fuses_conf_i, or_matrix_fuses_conf_i,
     outputs_o);
  input [0:0] inputs_i;
  input [7:0] and_matrix_fuses_conf_i;
  input [3:0] or_matrix_fuses_conf_i;
  output [0:0] outputs_o;
  wire [0:0] inputs_i;
  wire [7:0] and_matrix_fuses_conf_i;
  wire [3:0] or_matrix_fuses_conf_i;
  wire [0:0] outputs_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20;
  OR2_X1 g35__2398(.A1 (n_20), .A2 (n_19), .ZN (outputs_o));
  TINV_X1
       \gen_fuses_or[0].gen_any_port[0].gen_any_input[1].fuse_or_g1__5107
       (.EN (n_2), .I (n_18), .ZN (n_20));
  TINV_X1
       \gen_fuses_or[0].gen_any_port[1].gen_any_input[1].fuse_or_g1__6260
       (.EN (n_9), .I (n_17), .ZN (n_20));
  TINV_X1
       \gen_fuses_or[0].gen_any_port[0].gen_any_input[0].fuse_or_g1__4319
       (.EN (n_7), .I (n_18), .ZN (n_19));
  TINV_X1
       \gen_fuses_or[0].gen_any_port[1].gen_any_input[0].fuse_or_g1__8428
       (.EN (n_11), .I (n_17), .ZN (n_19));
  NAND2_X1 g36__5526(.A1 (n_16), .A2 (n_12), .ZN (n_18));
  NAND2_X1 g37__6783(.A1 (n_15), .A2 (n_14), .ZN (n_17));
  TINV_X1
       \gen_fuses_and[0].gen_any_port[0].gen_any_input[0].fuse_inverted_g1__3680
       (.EN (n_1), .I (inputs_i), .ZN (n_16));
  TINV_X1
       \gen_fuses_and[1].gen_any_port[0].gen_any_input[0].fuse_normal_g1__1617
       (.EN (n_3), .I (n_13), .ZN (n_15));
  TINV_X1
       \gen_fuses_and[1].gen_any_port[0].gen_any_input[0].fuse_inverted_g1__2802
       (.EN (n_6), .I (inputs_i), .ZN (n_15));
  TINV_X1
       \gen_fuses_and[1].gen_any_port[1].gen_any_input[0].fuse_normal_g1__1705
       (.EN (n_0), .I (n_13), .ZN (n_14));
  TINV_X1
       \gen_fuses_and[0].gen_any_port[1].gen_any_input[0].fuse_normal_g1__5122
       (.EN (n_5), .I (n_13), .ZN (n_12));
  TINV_X1
       \gen_fuses_and[1].gen_any_port[1].gen_any_input[0].fuse_inverted_g1__8246
       (.EN (n_4), .I (inputs_i), .ZN (n_14));
  TINV_X1
       \gen_fuses_and[0].gen_any_port[1].gen_any_input[0].fuse_inverted_g1__7098
       (.EN (n_8), .I (inputs_i), .ZN (n_12));
  TINV_X1
       \gen_fuses_and[0].gen_any_port[0].gen_any_input[0].fuse_normal_g1__6131
       (.EN (n_10), .I (n_13), .ZN (n_16));
  INV_X1 g48(.A (or_matrix_fuses_conf_i[2]), .ZN (n_11));
  INV_X1 g43(.A (and_matrix_fuses_conf_i[0]), .ZN (n_10));
  INV_X1 g49(.A (or_matrix_fuses_conf_i[3]), .ZN (n_9));
  INV_X1 g40(.A (and_matrix_fuses_conf_i[3]), .ZN (n_8));
  INV_X1 g41(.A (or_matrix_fuses_conf_i[0]), .ZN (n_7));
  INV_X1 g50(.A (inputs_i), .ZN (n_13));
  INV_X1 g47(.A (and_matrix_fuses_conf_i[5]), .ZN (n_6));
  INV_X1 g46(.A (and_matrix_fuses_conf_i[2]), .ZN (n_5));
  INV_X1 g42(.A (and_matrix_fuses_conf_i[7]), .ZN (n_4));
  INV_X1 g38(.A (and_matrix_fuses_conf_i[4]), .ZN (n_3));
  INV_X1 g44(.A (or_matrix_fuses_conf_i[1]), .ZN (n_2));
  INV_X1 g39(.A (and_matrix_fuses_conf_i[1]), .ZN (n_1));
  INV_X1 g45(.A (and_matrix_fuses_conf_i[6]), .ZN (n_0));
endmodule

// GENUS UID d37fa0eb34ee6115b71f12b7fe0b461f
