
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jul 13 2025 16:45:59 CEST (Jul 13 2025 14:45:59 UTC)

// Verification Directory fv/ripple_carry 

module ripple_carry(a_i, b_i, c_i, c_o, o_o);
  input [7:0] a_i, b_i;
  input c_i;
  output c_o;
  output [7:0] o_o;
  wire [7:0] a_i, b_i;
  wire c_i;
  wire c_o;
  wire [7:0] o_o;
  wire [8:0] C;
  wire [7:0] S;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_24, n_27, n_30, n_33, n_36, n_39, n_42, n_45;
  assign C[0] = c_i;
  assign o_o[0] = S[0];
  assign o_o[1] = S[1];
  assign o_o[2] = S[2];
  assign o_o[3] = S[3];
  assign o_o[4] = S[4];
  assign o_o[5] = S[5];
  assign o_o[6] = S[6];
  assign o_o[7] = S[7];
  assign c_o = C[8];
  INV_X1 g161(.A (n_7), .ZN (C[1]));
  AOI22_X1 g162__2398(.A1 (n_45), .A2 (C[0]), .B1 (a_i[0]), .B2
       (b_i[0]), .ZN (n_7));
  XOR2_X1 g163__5107(.A (b_i[0]), .B (a_i[0]), .Z (n_45));
  INV_X1 g164(.A (n_6), .ZN (C[2]));
  AOI22_X1 g165__6260(.A1 (C[1]), .A2 (n_42), .B1 (a_i[1]), .B2
       (b_i[1]), .ZN (n_6));
  XOR2_X1 g166__4319(.A (b_i[1]), .B (a_i[1]), .Z (n_42));
  INV_X1 g167(.A (n_5), .ZN (C[3]));
  AOI22_X1 g168__8428(.A1 (C[2]), .A2 (n_39), .B1 (a_i[2]), .B2
       (b_i[2]), .ZN (n_5));
  XOR2_X1 g169__5526(.A (b_i[2]), .B (a_i[2]), .Z (n_39));
  INV_X1 g170(.A (n_4), .ZN (C[4]));
  AOI22_X1 g171__6783(.A1 (C[3]), .A2 (n_36), .B1 (a_i[3]), .B2
       (b_i[3]), .ZN (n_4));
  XOR2_X1 g172__3680(.A (b_i[3]), .B (a_i[3]), .Z (n_36));
  INV_X1 g173(.A (n_3), .ZN (C[5]));
  AOI22_X1 g174__1617(.A1 (C[4]), .A2 (n_33), .B1 (a_i[4]), .B2
       (b_i[4]), .ZN (n_3));
  XOR2_X1 g175__2802(.A (b_i[4]), .B (a_i[4]), .Z (n_33));
  INV_X1 g176(.A (n_2), .ZN (C[6]));
  AOI22_X1 g177__1705(.A1 (C[5]), .A2 (n_30), .B1 (a_i[5]), .B2
       (b_i[5]), .ZN (n_2));
  XOR2_X1 g178__5122(.A (b_i[5]), .B (a_i[5]), .Z (n_30));
  INV_X1 g179(.A (n_1), .ZN (C[7]));
  AOI22_X1 g180__8246(.A1 (C[6]), .A2 (n_27), .B1 (a_i[6]), .B2
       (b_i[6]), .ZN (n_1));
  XOR2_X1 g181__7098(.A (b_i[6]), .B (a_i[6]), .Z (n_27));
  INV_X1 g182(.A (n_0), .ZN (C[8]));
  AOI22_X1 g183__6131(.A1 (C[7]), .A2 (n_24), .B1 (a_i[7]), .B2
       (b_i[7]), .ZN (n_0));
  XOR2_X1 g184__1881(.A (b_i[7]), .B (a_i[7]), .Z (n_24));
  XOR2_X1 g34_g113__5115(.A (C[4]), .B (n_33), .Z (S[4]));
  XOR2_X1 g34_g114__7482(.A (C[5]), .B (n_30), .Z (S[5]));
  XOR2_X1 g34_g115__4733(.A (C[7]), .B (n_24), .Z (S[7]));
  XOR2_X1 g34_g116__6161(.A (n_45), .B (C[0]), .Z (S[0]));
  XOR2_X1 g34_g117__9315(.A (C[2]), .B (n_39), .Z (S[2]));
  XOR2_X1 g34_g118__9945(.A (C[6]), .B (n_27), .Z (S[6]));
  XOR2_X1 g34_g119__2883(.A (C[3]), .B (n_36), .Z (S[3]));
  XOR2_X1 g34_g120__2346(.A (C[1]), .B (n_42), .Z (S[1]));
endmodule

// GENUS UID d37fa0eb34ee6115b71f12b7fe0b461f
