
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jul 12 2025 22:01:59 CEST (Jul 12 2025 20:01:59 UTC)

// Verification Directory fv/clocked_ripple_carry 

module ripple_carry_N8(a_i, b_i, c_i, c_o, o_o);
  input [7:0] a_i, b_i;
  input c_i;
  output c_o;
  output [7:0] o_o;
  wire [7:0] a_i, b_i;
  wire c_i;
  wire c_o;
  wire [7:0] o_o;
  wire [8:0] C;
  wire [7:0] S;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_26, n_29, n_32, n_35, n_38, n_41, n_44;
  wire n_47;
  assign C[0] = c_i;
  assign o_o[0] = S[0];
  assign o_o[1] = S[1];
  assign o_o[2] = S[2];
  assign o_o[3] = S[3];
  assign o_o[4] = S[4];
  assign o_o[5] = S[5];
  assign o_o[6] = S[6];
  assign o_o[7] = S[7];
  assign c_o = C[8];
  INV_X1 g219(.A (n_8), .ZN (C[2]));
  AOI22_X1 g220__2398(.A1 (C[1]), .A2 (n_44), .B1 (a_i[1]), .B2
       (b_i[1]), .ZN (n_8));
  XOR2_X1 g221__5107(.A (b_i[1]), .B (a_i[1]), .Z (n_44));
  NAND2_X1 g226__6260(.A1 (n_7), .A2 (n_6), .ZN (C[1]));
  OAI21_X1 g227__4319(.A (b_i[0]), .B1 (a_i[0]), .B2 (C[0]), .ZN (n_7));
  XOR2_X1 g228__8428(.A (b_i[0]), .B (a_i[0]), .Z (n_47));
  NAND2_X1 g229__5526(.A1 (a_i[0]), .A2 (C[0]), .ZN (n_6));
  INV_X1 g230(.A (n_5), .ZN (C[3]));
  AOI22_X1 g231__6783(.A1 (C[2]), .A2 (n_41), .B1 (a_i[2]), .B2
       (b_i[2]), .ZN (n_5));
  XOR2_X1 g232__3680(.A (b_i[2]), .B (a_i[2]), .Z (n_41));
  INV_X1 g233(.A (n_4), .ZN (C[4]));
  AOI22_X1 g234__1617(.A1 (C[3]), .A2 (n_38), .B1 (a_i[3]), .B2
       (b_i[3]), .ZN (n_4));
  XOR2_X1 g235__2802(.A (b_i[3]), .B (a_i[3]), .Z (n_38));
  INV_X1 g236(.A (n_3), .ZN (C[5]));
  AOI22_X1 g237__1705(.A1 (C[4]), .A2 (n_35), .B1 (a_i[4]), .B2
       (b_i[4]), .ZN (n_3));
  XOR2_X1 g238__5122(.A (b_i[4]), .B (a_i[4]), .Z (n_35));
  INV_X1 g239(.A (n_2), .ZN (C[6]));
  AOI22_X1 g240__8246(.A1 (C[5]), .A2 (n_32), .B1 (a_i[5]), .B2
       (b_i[5]), .ZN (n_2));
  XOR2_X1 g241__7098(.A (b_i[5]), .B (a_i[5]), .Z (n_32));
  INV_X1 g242(.A (n_1), .ZN (C[7]));
  AOI22_X1 g243__6131(.A1 (C[6]), .A2 (n_29), .B1 (a_i[6]), .B2
       (b_i[6]), .ZN (n_1));
  XOR2_X1 g244__1881(.A (b_i[6]), .B (a_i[6]), .Z (n_29));
  INV_X1 g245(.A (n_0), .ZN (C[8]));
  AOI22_X1 g246__5115(.A1 (C[7]), .A2 (n_26), .B1 (a_i[7]), .B2
       (b_i[7]), .ZN (n_0));
  XOR2_X1 g247__7482(.A (b_i[7]), .B (a_i[7]), .Z (n_26));
  XOR2_X1 g34_g113__4733(.A (C[4]), .B (n_35), .Z (S[4]));
  XOR2_X1 g34_g114__6161(.A (C[5]), .B (n_32), .Z (S[5]));
  XOR2_X1 g34_g115__9315(.A (C[7]), .B (n_26), .Z (S[7]));
  XOR2_X1 g34_g116__9945(.A (n_47), .B (C[0]), .Z (S[0]));
  XOR2_X1 g34_g117__2883(.A (C[2]), .B (n_41), .Z (S[2]));
  XOR2_X1 g34_g118__2346(.A (C[6]), .B (n_29), .Z (S[6]));
  XOR2_X1 g34_g119__1666(.A (C[3]), .B (n_38), .Z (S[3]));
  XOR2_X1 g34_g120__7410(.A (C[1]), .B (n_44), .Z (S[1]));
endmodule

module clocked_ripple_carry(a_i, b_i, clock_i, reset_ni,
     carry_out_register, out_register);
  input [7:0] a_i, b_i;
  input clock_i, reset_ni;
  output carry_out_register;
  output [7:0] out_register;
  wire [7:0] a_i, b_i;
  wire clock_i, reset_ni;
  wire carry_out_register;
  wire [7:0] out_register;
  wire [7:0] o_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, c_o, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8;
  ripple_carry_N8 i_dut(.a_i (a_i), .b_i (b_i), .c_i (1'b0), .c_o
       (c_o), .o_o (o_o));
  DFF_X1 \out_register_reg[5] (.CK (clock_i), .D (n_1), .Q
       (out_register[5]), .QN (UNCONNECTED));
  DFF_X1 \out_register_reg[7] (.CK (clock_i), .D (n_0), .Q
       (out_register[7]), .QN (UNCONNECTED0));
  DFF_X1 carry_out_register_reg(.CK (clock_i), .D (n_8), .Q
       (carry_out_register), .QN (UNCONNECTED1));
  DFF_X1 \out_register_reg[1] (.CK (clock_i), .D (n_3), .Q
       (out_register[1]), .QN (UNCONNECTED2));
  DFF_X1 \out_register_reg[6] (.CK (clock_i), .D (n_6), .Q
       (out_register[6]), .QN (UNCONNECTED3));
  DFF_X1 \out_register_reg[4] (.CK (clock_i), .D (n_7), .Q
       (out_register[4]), .QN (UNCONNECTED4));
  DFF_X1 \out_register_reg[0] (.CK (clock_i), .D (n_5), .Q
       (out_register[0]), .QN (UNCONNECTED5));
  DFF_X1 \out_register_reg[3] (.CK (clock_i), .D (n_4), .Q
       (out_register[3]), .QN (UNCONNECTED6));
  DFF_X1 \out_register_reg[2] (.CK (clock_i), .D (n_2), .Q
       (out_register[2]), .QN (UNCONNECTED7));
  AND2_X1 g38__6417(.A1 (c_o), .A2 (reset_ni), .ZN (n_8));
  AND2_X1 g39__5477(.A1 (o_o[4]), .A2 (reset_ni), .ZN (n_7));
  AND2_X1 g40__2398(.A1 (o_o[6]), .A2 (reset_ni), .ZN (n_6));
  AND2_X1 g41__5107(.A1 (o_o[0]), .A2 (reset_ni), .ZN (n_5));
  AND2_X1 g42__6260(.A1 (o_o[3]), .A2 (reset_ni), .ZN (n_4));
  AND2_X1 g43__4319(.A1 (o_o[1]), .A2 (reset_ni), .ZN (n_3));
  AND2_X1 g44__8428(.A1 (o_o[2]), .A2 (reset_ni), .ZN (n_2));
  AND2_X1 g45__5526(.A1 (o_o[5]), .A2 (reset_ni), .ZN (n_1));
  AND2_X1 g46__6783(.A1 (o_o[7]), .A2 (reset_ni), .ZN (n_0));
endmodule

// GENUS UID d37fa0eb34ee6115b71f12b7fe0b461f
