
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jun  8 2025 16:47:37 CEST (Jun  8 2025 14:47:37 UTC)

// Verification Directory fv/pipeline 

module avg(rst_ni, clk_i, data_i, data_o);
  input rst_ni, clk_i;
  input [7:0] data_i;
  output [7:0] data_o;
  wire rst_ni, clk_i;
  wire [7:0] data_i;
  wire [7:0] data_o;
  wire [7:0] measurement_previous;
  wire [7:0] measurement_pre_previous;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire csa_tree_ADD_TC_OP_1_groupi_n_0,
       csa_tree_ADD_TC_OP_1_groupi_n_1,
       csa_tree_ADD_TC_OP_1_groupi_n_2,
       csa_tree_ADD_TC_OP_1_groupi_n_3,
       csa_tree_ADD_TC_OP_1_groupi_n_4,
       csa_tree_ADD_TC_OP_1_groupi_n_5,
       csa_tree_ADD_TC_OP_1_groupi_n_6, csa_tree_ADD_TC_OP_1_groupi_n_7;
  wire csa_tree_ADD_TC_OP_1_groupi_n_8,
       csa_tree_ADD_TC_OP_1_groupi_n_9,
       csa_tree_ADD_TC_OP_1_groupi_n_10,
       csa_tree_ADD_TC_OP_1_groupi_n_11,
       csa_tree_ADD_TC_OP_1_groupi_n_12,
       csa_tree_ADD_TC_OP_1_groupi_n_13,
       csa_tree_ADD_TC_OP_1_groupi_n_14,
       csa_tree_ADD_TC_OP_1_groupi_n_15;
  wire csa_tree_ADD_TC_OP_1_groupi_n_16,
       csa_tree_ADD_TC_OP_1_groupi_n_17,
       csa_tree_ADD_TC_OP_1_groupi_n_18,
       csa_tree_ADD_TC_OP_1_groupi_n_19,
       csa_tree_ADD_TC_OP_1_groupi_n_20,
       csa_tree_ADD_TC_OP_1_groupi_n_21,
       csa_tree_ADD_TC_OP_1_groupi_n_22,
       csa_tree_ADD_TC_OP_1_groupi_n_23;
  wire csa_tree_ADD_TC_OP_1_groupi_n_24,
       csa_tree_ADD_TC_OP_1_groupi_n_25,
       csa_tree_ADD_TC_OP_1_groupi_n_26,
       csa_tree_ADD_TC_OP_1_groupi_n_27,
       csa_tree_ADD_TC_OP_1_groupi_n_29,
       csa_tree_ADD_TC_OP_1_groupi_n_30,
       csa_tree_ADD_TC_OP_1_groupi_n_31,
       csa_tree_ADD_TC_OP_1_groupi_n_32;
  wire csa_tree_ADD_TC_OP_1_groupi_n_33,
       csa_tree_ADD_TC_OP_1_groupi_n_34,
       csa_tree_ADD_TC_OP_1_groupi_n_35,
       csa_tree_ADD_TC_OP_1_groupi_n_36,
       csa_tree_ADD_TC_OP_1_groupi_n_37,
       csa_tree_ADD_TC_OP_1_groupi_n_38,
       csa_tree_ADD_TC_OP_1_groupi_n_39,
       csa_tree_ADD_TC_OP_1_groupi_n_40;
  wire csa_tree_ADD_TC_OP_1_groupi_n_41,
       csa_tree_ADD_TC_OP_1_groupi_n_42,
       csa_tree_ADD_TC_OP_1_groupi_n_43,
       csa_tree_ADD_TC_OP_1_groupi_n_45,
       csa_tree_ADD_TC_OP_1_groupi_n_46,
       csa_tree_ADD_TC_OP_1_groupi_n_47,
       csa_tree_ADD_TC_OP_1_groupi_n_48,
       csa_tree_ADD_TC_OP_1_groupi_n_49;
  wire csa_tree_ADD_TC_OP_1_groupi_n_50,
       csa_tree_ADD_TC_OP_1_groupi_n_51,
       csa_tree_ADD_TC_OP_1_groupi_n_52,
       csa_tree_ADD_TC_OP_1_groupi_n_53,
       csa_tree_ADD_TC_OP_1_groupi_n_55,
       csa_tree_ADD_TC_OP_1_groupi_n_56,
       csa_tree_ADD_TC_OP_1_groupi_n_57,
       csa_tree_ADD_TC_OP_1_groupi_n_59;
  wire csa_tree_ADD_TC_OP_1_groupi_n_60,
       csa_tree_ADD_TC_OP_1_groupi_n_61,
       csa_tree_ADD_TC_OP_1_groupi_n_62,
       csa_tree_ADD_TC_OP_1_groupi_n_63,
       csa_tree_ADD_TC_OP_1_groupi_n_64,
       csa_tree_ADD_TC_OP_1_groupi_n_65,
       csa_tree_ADD_TC_OP_1_groupi_n_66,
       csa_tree_ADD_TC_OP_1_groupi_n_67;
  wire csa_tree_ADD_TC_OP_1_groupi_n_69,
       csa_tree_ADD_TC_OP_1_groupi_n_70,
       csa_tree_ADD_TC_OP_1_groupi_n_71,
       csa_tree_ADD_TC_OP_1_groupi_n_72,
       csa_tree_ADD_TC_OP_1_groupi_n_74,
       csa_tree_ADD_TC_OP_1_groupi_n_76,
       csa_tree_ADD_TC_OP_1_groupi_n_78, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_161, n_162;
  DFFRS_X1 \data_o_reg[0] (.RN (n_25), .SN (n_35), .CK (clk_i), .D
       (n_136), .Q (data_o[0]), .QN (UNCONNECTED));
  DFFRS_X1 \data_o_reg[1] (.RN (n_24), .SN (n_39), .CK (clk_i), .D
       (n_140), .Q (data_o[1]), .QN (UNCONNECTED0));
  DFFRS_X1 \data_o_reg[2] (.RN (n_28), .SN (n_34), .CK (clk_i), .D
       (n_138), .Q (data_o[2]), .QN (UNCONNECTED1));
  DFFRS_X1 \data_o_reg[3] (.RN (n_21), .SN (n_37), .CK (clk_i), .D
       (n_137), .Q (data_o[3]), .QN (UNCONNECTED2));
  DFFRS_X1 \data_o_reg[4] (.RN (n_27), .SN (n_36), .CK (clk_i), .D
       (n_120), .Q (data_o[4]), .QN (UNCONNECTED3));
  DFFRS_X1 \data_o_reg[5] (.RN (n_42), .SN (n_41), .CK (clk_i), .D
       (n_129), .Q (data_o[5]), .QN (UNCONNECTED4));
  DFFRS_X1 \data_o_reg[6] (.RN (n_26), .SN (n_40), .CK (clk_i), .D
       (n_119), .Q (data_o[6]), .QN (UNCONNECTED5));
  DFFRS_X1 \data_o_reg[7] (.RN (n_29), .SN (n_38), .CK (clk_i), .D
       (n_161), .Q (data_o[7]), .QN (UNCONNECTED6));
  DFFRS_X1 \measurement_pre_previous_reg[0] (.RN (n_25), .SN (n_35),
       .CK (clk_i), .D (measurement_previous[0]), .Q
       (measurement_pre_previous[0]), .QN (UNCONNECTED7));
  DFFRS_X1 \measurement_pre_previous_reg[1] (.RN (n_24), .SN (n_39),
       .CK (clk_i), .D (measurement_previous[1]), .Q
       (measurement_pre_previous[1]), .QN (UNCONNECTED8));
  DFFRS_X1 \measurement_pre_previous_reg[2] (.RN (n_28), .SN (n_34),
       .CK (clk_i), .D (measurement_previous[2]), .Q
       (measurement_pre_previous[2]), .QN (UNCONNECTED9));
  DFFRS_X1 \measurement_pre_previous_reg[3] (.RN (n_21), .SN (n_37),
       .CK (clk_i), .D (measurement_previous[3]), .Q
       (measurement_pre_previous[3]), .QN (UNCONNECTED10));
  DFFRS_X1 \measurement_pre_previous_reg[4] (.RN (n_27), .SN (n_36),
       .CK (clk_i), .D (measurement_previous[4]), .Q
       (measurement_pre_previous[4]), .QN (UNCONNECTED11));
  DFFRS_X1 \measurement_pre_previous_reg[5] (.RN (n_42), .SN (n_41),
       .CK (clk_i), .D (measurement_previous[5]), .Q
       (measurement_pre_previous[5]), .QN (UNCONNECTED12));
  DFFRS_X1 \measurement_pre_previous_reg[6] (.RN (n_26), .SN (n_40),
       .CK (clk_i), .D (measurement_previous[6]), .Q
       (measurement_pre_previous[6]), .QN (UNCONNECTED13));
  DFFRS_X1 \measurement_pre_previous_reg[7] (.RN (n_29), .SN (n_38),
       .CK (clk_i), .D (measurement_previous[7]), .Q
       (measurement_pre_previous[7]), .QN (UNCONNECTED14));
  DFFRS_X1 \measurement_previous_reg[0] (.RN (n_25), .SN (n_35), .CK
       (clk_i), .D (data_i[0]), .Q (measurement_previous[0]), .QN
       (UNCONNECTED15));
  DFFRS_X1 \measurement_previous_reg[1] (.RN (n_24), .SN (n_39), .CK
       (clk_i), .D (data_i[1]), .Q (measurement_previous[1]), .QN
       (UNCONNECTED16));
  DFFRS_X1 \measurement_previous_reg[2] (.RN (n_28), .SN (n_34), .CK
       (clk_i), .D (data_i[2]), .Q (measurement_previous[2]), .QN
       (UNCONNECTED17));
  DFFRS_X1 \measurement_previous_reg[3] (.RN (n_21), .SN (n_37), .CK
       (clk_i), .D (data_i[3]), .Q (measurement_previous[3]), .QN
       (UNCONNECTED18));
  DFFRS_X1 \measurement_previous_reg[4] (.RN (n_27), .SN (n_36), .CK
       (clk_i), .D (data_i[4]), .Q (measurement_previous[4]), .QN
       (UNCONNECTED19));
  DFFRS_X1 \measurement_previous_reg[5] (.RN (n_42), .SN (n_41), .CK
       (clk_i), .D (data_i[5]), .Q (measurement_previous[5]), .QN
       (UNCONNECTED20));
  DFFRS_X1 \measurement_previous_reg[6] (.RN (n_26), .SN (n_40), .CK
       (clk_i), .D (data_i[6]), .Q (measurement_previous[6]), .QN
       (UNCONNECTED21));
  DFFRS_X1 \measurement_previous_reg[7] (.RN (n_29), .SN (n_38), .CK
       (clk_i), .D (data_i[7]), .Q (measurement_previous[7]), .QN
       (UNCONNECTED22));
  OAI221_X1 g177894__2398(.A (n_139), .B1 (n_131), .B2 (n_146), .C1
       (n_106), .C2 (n_61), .ZN (n_140));
  AOI221_X1 g177896__5107(.A (n_133), .B1 (n_111), .B2 (n_151), .C1
       (n_135), .C2 (n_22), .ZN (n_139));
  OAI21_X1 g177899__6260(.A (n_128), .B1 (n_134), .B2 (n_60), .ZN
       (n_138));
  NAND3_X1 g177900__4319(.A1 (n_127), .A2 (n_126), .A3 (n_97), .ZN
       (n_137));
  OAI211_X1 g177901__8428(.A (n_132), .B (n_125), .C1 (n_116), .C2
       (n_65), .ZN (n_136));
  OAI22_X1 g177902__5526(.A1 (n_124), .A2 (n_6), .B1 (n_116), .B2
       (n_146), .ZN (n_135));
  AOI21_X1 g177905__6783(.A (n_115), .B1 (n_123), .B2 (n_143), .ZN
       (n_134));
  AOI211_X1 g177906__3680(.A (n_57), .B (n_112), .C1 (n_121), .C2
       (n_11), .ZN (n_133));
  AOI22_X1 g177907__1617(.A1 (n_117), .A2 (n_64), .B1 (n_118), .B2
       (n_45), .ZN (n_132));
  AOI222_X1 g177908__2802(.A1 (n_117), .A2 (n_2), .B1 (n_74), .B2
       (n_66), .C1 (n_75), .C2 (n_68), .ZN (n_131));
  OAI221_X1 g177912__5122(.A (n_113), .B1 (n_71), .B2 (n_84), .C1
       (n_59), .C2 (n_91), .ZN (n_129));
  NAND3_X1 g177913__8246(.A1 (n_118), .A2 (n_146), .A3 (n_11), .ZN
       (n_128));
  AOI22_X1 g177914__7098(.A1 (n_108), .A2 (n_144), .B1 (n_74), .B2
       (n_95), .ZN (n_127));
  OAI21_X1 g177915__6131(.A (n_96), .B1 (n_109), .B2 (n_20), .ZN
       (n_126));
  NAND3_X1 g177916__1881(.A1 (n_114), .A2 (n_44), .A3 (n_141), .ZN
       (n_125));
  AOI21_X1 g177917__5115(.A (n_98), .B1 (n_103), .B2 (n_143), .ZN
       (n_124));
  INV_X1 g177918(.A (n_122), .ZN (n_123));
  AOI221_X1 g177919__7482(.A (n_85), .B1 (n_89), .B2 (n_47), .C1
       (n_87), .C2 (n_20), .ZN (n_122));
  NAND2_X1 g177920__4733(.A1 (n_104), .A2 (n_146), .ZN (n_121));
  OAI33_X1 g177921__6161(.A1 (n_100), .A2 (n_74), .A3 (n_81), .B1
       (n_73), .B2 (n_6), .B3 (n_69), .ZN (n_120));
  OAI222_X1 g177922__9315(.A1 (n_71), .A2 (n_82), .B1 (n_90), .B2
       (n_31), .C1 (n_59), .C2 (n_146), .ZN (n_119));
  INV_X1 g177923(.A (n_116), .ZN (n_115));
  OAI221_X1 g177924__9945(.A (n_99), .B1 (n_73), .B2 (n_13), .C1
       (n_75), .C2 (n_15), .ZN (n_114));
  AOI221_X1 g177925__2883(.A (n_92), .B1 (n_90), .B2 (n_30), .C1
       (n_80), .C2 (n_6), .ZN (n_113));
  OAI22_X1 g177926__2346(.A1 (n_93), .A2 (n_101), .B1 (n_86), .B2
       (n_15), .ZN (n_118));
  OAI22_X1 g177927__1666(.A1 (n_94), .A2 (n_102), .B1 (n_86), .B2
       (n_12), .ZN (n_117));
  AOI21_X1 g177928__7410(.A (n_105), .B1 (n_87), .B2 (n_53), .ZN
       (n_116));
  AOI21_X1 g177929__6417(.A (n_11), .B1 (n_87), .B2 (n_0), .ZN (n_112));
  OAI22_X1 g177930__5477(.A1 (n_86), .A2 (n_67), .B1 (n_73), .B2
       (n_61), .ZN (n_111));
  AOI221_X1 g177932__5107(.A (n_151), .B1 (n_57), .B2 (n_144), .C1
       (n_88), .C2 (n_6), .ZN (n_109));
  INV_X1 g177933(.A (n_107), .ZN (n_108));
  AOI22_X1 g177934__6260(.A1 (n_87), .A2 (n_6), .B1 (n_76), .B2 (n_20),
       .ZN (n_107));
  AOI22_X1 g177935__4319(.A1 (n_87), .A2 (n_12), .B1 (n_77), .B2
       (n_14), .ZN (n_106));
  AOI22_X1 g177936__8428(.A1 (n_88), .A2 (n_12), .B1 (n_73), .B2
       (n_15), .ZN (n_105));
  NOR2_X1 g177937__5526(.A1 (n_93), .A2 (n_101), .ZN (n_104));
  NOR2_X1 g177938__6783(.A1 (n_94), .A2 (n_102), .ZN (n_103));
  NOR2_X1 g177939__3680(.A1 (n_89), .A2 (n_14), .ZN (n_102));
  NOR2_X1 g177940__1617(.A1 (n_87), .A2 (n_20), .ZN (n_100));
  NAND2_X1 g177941__2802(.A1 (n_89), .A2 (n_151), .ZN (n_99));
  NOR2_X1 g177942__1705(.A1 (n_89), .A2 (n_53), .ZN (n_101));
  NOR3_X1 g177943__5122(.A1 (n_86), .A2 (n_15), .A3 (n_10), .ZN (n_98));
  OAI211_X1 g177944__8246(.A (n_89), .B (n_146), .C1 (n_9), .C2 (n_55),
       .ZN (n_97));
  OAI21_X1 g177945__7098(.A (n_86), .B1 (n_146), .B2 (n_151), .ZN
       (n_96));
  AOI22_X1 g177946__6131(.A1 (n_79), .A2 (n_58), .B1 (n_53), .B2
       (n_55), .ZN (n_95));
  NOR3_X1 g177947__1881(.A1 (n_71), .A2 (n_70), .A3 (n_149), .ZN
       (n_92));
  NOR2_X1 g177948__5115(.A1 (n_74), .A2 (n_53), .ZN (n_94));
  NOR2_X1 g177949__7482(.A1 (n_74), .A2 (n_13), .ZN (n_93));
  OAI21_X1 g177950__4733(.A (n_146), .B1 (n_69), .B2 (n_150), .ZN
       (n_91));
  INV_X1 g177951(.A (n_89), .ZN (n_88));
  INV_X1 g177952(.A (n_87), .ZN (n_86));
  NOR3_X1 g177953__6161(.A1 (n_78), .A2 (n_146), .A3 (n_15), .ZN
       (n_85));
  AOI21_X1 g177954__9315(.A (n_56), .B1 (n_70), .B2 (n_149), .ZN
       (n_84));
  AOI211_X1 g177955__9945(.A (n_149), .B (n_6), .C1 (n_69), .C2
       (n_150), .ZN (n_90));
  OAI222_X1 g177956__2883(.A1 (n_51), .A2 (n_19), .B1 (n_33), .B2
       (n_56), .C1 (n_31), .C2 (n_17), .ZN (n_89));
  OAI221_X1 g177957__2346(.A (n_62), .B1 (n_51), .B2 (n_17), .C1
       (n_31), .C2 (n_56), .ZN (n_87));
  INV_X1 g177958(.A (n_82), .ZN (n_83));
  AOI211_X1 g177959__1666(.A (n_151), .B (n_6), .C1 (n_144), .C2
       (n_10), .ZN (n_81));
  OAI221_X1 g177960__7410(.A (n_48), .B1 (n_32), .B2 (n_46), .C1
       (n_33), .C2 (n_149), .ZN (n_80));
  OAI21_X1 g177961__6417(.A (n_146), .B1 (n_52), .B2 (n_151), .ZN
       (n_79));
  NOR2_X1 g177962__5477(.A1 (n_46), .A2 (n_70), .ZN (n_82));
  INV_X1 g177963(.A (n_72), .ZN (n_78));
  INV_X1 g177964(.A (n_76), .ZN (n_77));
  INV_X1 g177965(.A (n_74), .ZN (n_73));
  OAI221_X1 g177966__2398(.A (n_59), .B1 (n_51), .B2 (n_16), .C1 (n_3),
       .C2 (n_19), .ZN (n_72));
  OAI222_X1 g177967__5107(.A1 (n_51), .A2 (n_18), .B1 (n_147), .B2
       (n_17), .C1 (n_31), .C2 (n_149), .ZN (n_76));
  AOI221_X1 g177968__6260(.A (n_63), .B1 (n_30), .B2 (n_17), .C1
       (n_50), .C2 (n_149), .ZN (n_75));
  OAI222_X1 g177969__4319(.A1 (n_51), .A2 (n_56), .B1 (n_33), .B2
       (n_17), .C1 (n_31), .C2 (n_19), .ZN (n_74));
  INV_X1 g177970(.A (n_70), .ZN (n_69));
  NOR2_X1 g177971__8428(.A1 (n_54), .A2 (n_144), .ZN (n_68));
  NAND2_X1 g177972__5526(.A1 (n_50), .A2 (n_146), .ZN (n_71));
  NAND2_X1 g177973__6783(.A1 (n_55), .A2 (n_144), .ZN (n_70));
  NAND3_X1 g177974__3680(.A1 (n_146), .A2 (n_13), .A3 (n_143), .ZN
       (n_67));
  OAI21_X1 g177975__1617(.A (n_54), .B1 (n_144), .B2 (n_11), .ZN
       (n_66));
  AOI211_X1 g177976__2802(.A (n_10), .B (n_23), .C1 (n_143), .C2
       (n_141), .ZN (n_65));
  OAI21_X1 g177977__1705(.A (n_43), .B1 (n_45), .B2 (n_5), .ZN (n_64));
  INV_X1 g177991(.A (n_62), .ZN (n_63));
  INV_X1 g177992(.A (n_61), .ZN (n_60));
  INV_X1 g177993(.A (n_57), .ZN (n_58));
  INV_X1 g177994(.A (n_55), .ZN (n_54));
  INV_X1 g177995(.A (n_53), .ZN (n_52));
  INV_X1 g177996(.A (n_51), .ZN (n_50));
  OAI21_X1 g177998__5122(.A (n_30), .B1 (n_149), .B2 (n_150), .ZN
       (n_48));
  NOR2_X1 g177999__8246(.A1 (n_146), .A2 (n_13), .ZN (n_47));
  NAND2_X1 g178002__7098(.A1 (n_32), .A2 (n_18), .ZN (n_62));
  NAND2_X1 g178004__6131(.A1 (n_146), .A2 (n_23), .ZN (n_61));
  NAND2_X1 g178005__1881(.A1 (n_32), .A2 (n_149), .ZN (n_59));
  NOR2_X1 g178006__5115(.A1 (n_6), .A2 (n_11), .ZN (n_57));
  NAND2_X1 g178007__7482(.A1 (n_17), .A2 (n_19), .ZN (n_56));
  NOR2_X1 g178008__4733(.A1 (n_0), .A2 (n_11), .ZN (n_55));
  NOR2_X1 g178009__6161(.A1 (n_14), .A2 (n_13), .ZN (n_53));
  NAND2_X1 g178010__9315(.A1 (n_33), .A2 (n_31), .ZN (n_51));
  INV_X1 g178011(.A (n_43), .ZN (n_44));
  INV_X1 g178012(.A (n_33), .ZN (n_32));
  INV_X1 g178013(.A (n_31), .ZN (n_30));
  NAND2_X1 g178014__9945(.A1 (n_149), .A2 (n_150), .ZN (n_46));
  NOR2_X1 g178015__2883(.A1 (n_2), .A2 (n_142), .ZN (n_45));
  NAND2_X1 g178016__2346(.A1 (n_2), .A2 (n_142), .ZN (n_43));
  OR2_X1 g178017__1666(.A1 (rst_ni), .A2 (data_i[5]), .ZN (n_42));
  NAND2_X1 g178018__7410(.A1 (n_7), .A2 (data_i[5]), .ZN (n_41));
  NAND2_X1 g178019__6417(.A1 (n_7), .A2 (data_i[6]), .ZN (n_40));
  NAND2_X1 g178020__5477(.A1 (n_7), .A2 (data_i[1]), .ZN (n_39));
  NAND2_X1 g178021__2398(.A1 (n_7), .A2 (data_i[7]), .ZN (n_38));
  NAND2_X1 g178022__5107(.A1 (n_7), .A2 (data_i[3]), .ZN (n_37));
  NAND2_X1 g178023__6260(.A1 (n_7), .A2 (data_i[4]), .ZN (n_36));
  NAND2_X1 g178024__4319(.A1 (n_7), .A2 (data_i[0]), .ZN (n_35));
  NAND2_X1 g178025__8428(.A1 (n_7), .A2 (data_i[2]), .ZN (n_34));
  NAND2_X1 g178026__5526(.A1 (n_3), .A2 (n_148), .ZN (n_33));
  OR2_X1 g178027__6783(.A1 (n_3), .A2 (n_148), .ZN (n_31));
  INV_X1 g178028(.A (n_23), .ZN (n_22));
  INV_X1 g178029(.A (n_19), .ZN (n_18));
  INV_X1 g178030(.A (n_17), .ZN (n_16));
  INV_X1 g178031(.A (n_15), .ZN (n_14));
  INV_X1 g178032(.A (n_13), .ZN (n_12));
  INV_X1 g178033(.A (n_11), .ZN (n_10));
  NOR2_X1 g178034__3680(.A1 (n_0), .A2 (n_8), .ZN (n_9));
  OR2_X1 g178035__1617(.A1 (rst_ni), .A2 (data_i[7]), .ZN (n_29));
  OR2_X1 g178036__2802(.A1 (rst_ni), .A2 (data_i[2]), .ZN (n_28));
  OR2_X1 g178037__1705(.A1 (rst_ni), .A2 (data_i[4]), .ZN (n_27));
  OR2_X1 g178038__5122(.A1 (rst_ni), .A2 (data_i[6]), .ZN (n_26));
  OR2_X1 g178039__8246(.A1 (rst_ni), .A2 (data_i[0]), .ZN (n_25));
  OR2_X1 g178040__7098(.A1 (rst_ni), .A2 (data_i[1]), .ZN (n_24));
  NOR2_X1 g178041__6131(.A1 (n_143), .A2 (n_142), .ZN (n_23));
  OR2_X1 g178042__1881(.A1 (rst_ni), .A2 (data_i[3]), .ZN (n_21));
  NOR2_X1 g178043__5115(.A1 (n_146), .A2 (n_0), .ZN (n_20));
  NAND2_X1 g178044__7482(.A1 (n_1), .A2 (n_150), .ZN (n_19));
  NAND2_X1 g178045__4733(.A1 (n_4), .A2 (n_149), .ZN (n_17));
  NAND2_X1 g178046__6161(.A1 (n_0), .A2 (n_144), .ZN (n_15));
  NOR2_X1 g178047__9315(.A1 (n_0), .A2 (n_144), .ZN (n_13));
  NAND2_X1 g178048__9945(.A1 (n_143), .A2 (n_142), .ZN (n_11));
  INV_X1 g178049(.A (n_144), .ZN (n_8));
  INV_X1 g178050(.A (rst_ni), .ZN (n_7));
  INV_X1 g178051(.A (n_146), .ZN (n_6));
  INV_X1 g178052(.A (n_141), .ZN (n_5));
  INV_X1 g178053(.A (n_150), .ZN (n_4));
  INV_X1 g178054(.A (n_147), .ZN (n_3));
  INV_X1 g178055(.A (n_143), .ZN (n_2));
  INV_X1 g178056(.A (n_149), .ZN (n_1));
  INV_X1 g178057(.A (n_151), .ZN (n_0));
  AOI21_X2 csa_tree_ADD_TC_OP_1_groupi_g446__2883(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_33), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_78), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_32), .ZN (n_146));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g447__2346(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_78), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_38), .ZN (n_147));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g448__1666(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_42), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_76), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_39), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_78));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g449__7410(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_76), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_49), .ZN (n_148));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g450__6417(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_63), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_74), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_67), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_76));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g451__5477(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_74), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_71), .ZN (n_149));
  OAI211_X1 csa_tree_ADD_TC_OP_1_groupi_g452__2398(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_72), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_66), .C1
       (csa_tree_ADD_TC_OP_1_groupi_n_65), .C2
       (csa_tree_ADD_TC_OP_1_groupi_n_57), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_74));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g453__5107(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_69), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_70), .ZN (n_150));
  OR3_X1 csa_tree_ADD_TC_OP_1_groupi_g454__6260(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_60), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_65), .A3
       (csa_tree_ADD_TC_OP_1_groupi_n_55), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_72));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g455__4319(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_67), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_27), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_71));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g456__8428(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_64), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_66), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_70));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g457__5526(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_57), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_60), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_55), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_69));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g458__6783(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_60), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_62), .ZN (n_151));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g459__3680(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_67));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g460__1617(.A1 (data_i[5]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_59), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_66));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g461(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_65), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_64));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g462__2802(.A1 (data_i[5]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_59), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_65));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g463__1705(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_63));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g464__5122(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_55), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_56), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_62));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g465__8246(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_52), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_4), .B1
       (measurement_pre_previous[5]), .B2 (measurement_previous[5]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_61));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g466__7098(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_47), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_51), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_45), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_60));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g467__6131(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_52), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_16), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_59));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g468__1881(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_51), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_53), .ZN (n_144));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g469(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_57), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_56));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g470__5115(.A1 (data_i[4]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_50), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_57));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g471__7482(.A1 (data_i[4]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_50), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_55));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g472__4733(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_35), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_48), .ZN (n_143));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g473__6161(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_45), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_46), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_53));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g474__9315(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_5), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_37), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_2), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_52));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g475__9945(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_43), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_36), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_40), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_51));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g476__2883(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_14), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_37), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_50));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g477__2346(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_39), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_41), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_49));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g478__1666(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_43), .B1 (data_i[2]), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_29), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_48));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g479(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_46), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_47));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g480__7410(.A1 (data_i[3]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_34), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_46));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g481__6417(.A1 (data_i[3]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_34), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_45));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g482__5477(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_22), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_31), .ZN (n_142));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g483__2398(.A1 (data_i[2]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_29), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_43));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g484(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_41), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_42));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g485__5107(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_23), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_30), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_41));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g486__6260(.A1 (data_i[2]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_29), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_40));
  AND2_X1 csa_tree_ADD_TC_OP_1_groupi_g487__4319(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_23), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_30), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_39));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g488__8428(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_32), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_20), .B2
       (measurement_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_38));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g489__5526(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_21), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_1), .B1
       (measurement_pre_previous[3]), .B2 (measurement_previous[3]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_37));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g490(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_35), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_36));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g491__6783(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_24), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_22), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_26), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_35));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g492__3680(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_13), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_21), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_34));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g493__1617(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_20), .A2
       (measurement_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_33));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g494__2802(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_20), .A2
       (measurement_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_32));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g495__1705(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_26), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_25), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_31));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g496__5122(.A (data_i[7]), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_18), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_30));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g497__8246(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_15), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_29));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g498__7098(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_12), .B
       (measurement_pre_previous[0]), .ZN (n_141));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g499__6131(.A (data_i[6]), .B
       (csa_tree_ADD_TC_OP_1_groupi_n_17), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_27));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g500__1881(.A1 (data_i[1]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_19), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_26));
  INV_X1 csa_tree_ADD_TC_OP_1_groupi_g501(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_24), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_25));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g502__5115(.A1 (data_i[1]), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_19), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_24));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g503__7482(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_10), .A2
       (measurement_previous[6]), .B1 (data_i[6]), .B2
       (measurement_pre_previous[6]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_23));
  AOI22_X1 csa_tree_ADD_TC_OP_1_groupi_g504__4733(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_9), .A2
       (measurement_previous[0]), .B1 (data_i[0]), .B2
       (measurement_pre_previous[0]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_22));
  OAI21_X1 csa_tree_ADD_TC_OP_1_groupi_g505__6161(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_0), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_6), .B2
       (csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_21));
  AOI21_X1 csa_tree_ADD_TC_OP_1_groupi_g506__9315(.A
       (csa_tree_ADD_TC_OP_1_groupi_n_3), .B1
       (csa_tree_ADD_TC_OP_1_groupi_n_7), .B2
       (measurement_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_20));
  AND2_X1 csa_tree_ADD_TC_OP_1_groupi_g507__9945(.A1
       (csa_tree_ADD_TC_OP_1_groupi_n_8), .A2
       (csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_19));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g508__2883(.A
       (measurement_previous[7]), .B (measurement_pre_previous[7]), .Z
       (csa_tree_ADD_TC_OP_1_groupi_n_18));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g509__2346(.A
       (measurement_previous[6]), .B (measurement_pre_previous[6]), .Z
       (csa_tree_ADD_TC_OP_1_groupi_n_17));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g510__1666(.A
       (measurement_previous[5]), .B (measurement_pre_previous[5]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_16));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g511__7410(.A
       (measurement_previous[2]), .B (measurement_pre_previous[2]), .Z
       (csa_tree_ADD_TC_OP_1_groupi_n_15));
  XOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g512__6417(.A
       (measurement_previous[4]), .B (measurement_pre_previous[4]), .Z
       (csa_tree_ADD_TC_OP_1_groupi_n_14));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g513__5477(.A
       (measurement_previous[3]), .B (measurement_pre_previous[3]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_13));
  XNOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g514__2398(.A (data_i[0]), .B
       (measurement_previous[0]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_12));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g515__5107(.A1 (data_i[6]), .A2
       (measurement_pre_previous[6]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_10));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g516__6260(.A1 (data_i[0]), .A2
       (measurement_pre_previous[0]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_9));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g517__4319(.A1
       (measurement_previous[1]), .A2 (measurement_pre_previous[1]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_8));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g518__8428(.A1 (data_i[7]), .A2
       (measurement_pre_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_7));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g519__5526(.A1
       (measurement_previous[2]), .A2 (measurement_pre_previous[2]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_6));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g520__6783(.A1
       (measurement_previous[1]), .A2 (measurement_pre_previous[1]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_11));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g521__3680(.A1
       (measurement_previous[4]), .A2 (measurement_pre_previous[4]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_5));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g522__1617(.A1
       (measurement_previous[5]), .A2 (measurement_pre_previous[5]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_4));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g523__2802(.A1 (data_i[7]), .A2
       (measurement_pre_previous[7]), .ZN
       (csa_tree_ADD_TC_OP_1_groupi_n_3));
  NOR2_X1 csa_tree_ADD_TC_OP_1_groupi_g524__1705(.A1
       (measurement_previous[4]), .A2 (measurement_pre_previous[4]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_2));
  OR2_X1 csa_tree_ADD_TC_OP_1_groupi_g525__5122(.A1
       (measurement_previous[3]), .A2 (measurement_pre_previous[3]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_1));
  NAND2_X1 csa_tree_ADD_TC_OP_1_groupi_g526__8246(.A1
       (measurement_previous[2]), .A2 (measurement_pre_previous[2]),
       .ZN (csa_tree_ADD_TC_OP_1_groupi_n_0));
  NOR2_X1 g2(.A1 (n_162), .A2 (n_6), .ZN (n_161));
  NOR2_X1 g178058(.A1 (n_51), .A2 (n_83), .ZN (n_162));
endmodule

module pipeline(rst_ni, clock_slow, clock_fast, temperature,
     fourteen_seg_o);
  input rst_ni, clock_slow, clock_fast;
  input [7:0] temperature;
  output [14:0] fourteen_seg_o;
  wire rst_ni, clock_slow, clock_fast;
  wire [7:0] temperature;
  wire [14:0] fourteen_seg_o;
  wire [7:0] avg_out;
  wire [7:0] \gen_cdc.i_cdc_register_slow_1 ;
  wire [7:0] cdc_out;
  wire [31:0] i_seg_display_current_state;
  wire [7:0] \gen_cdc.i_cdc_register_fast ;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, i_seg_display_n_751;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_30, n_31, n_32;
  wire n_37, n_38;
  assign fourteen_seg_o[1] = 1'b0;
  assign fourteen_seg_o[3] = fourteen_seg_o[11];
  assign fourteen_seg_o[7] = 1'b0;
  assign fourteen_seg_o[10] = 1'b1;
  assign fourteen_seg_o[12] = 1'b1;
  assign fourteen_seg_o[13] = 1'b0;
  assign fourteen_seg_o[14] = 1'b0;
  avg avg(.rst_ni (rst_ni), .clk_i (clock_fast), .data_i (temperature),
       .data_o (avg_out));
  INV_X1 g430(.A (fourteen_seg_o[9]), .ZN (fourteen_seg_o[0]));
  INV_X1 g429(.A (fourteen_seg_o[8]), .ZN (fourteen_seg_o[6]));
  OAI21_X1 g539__7098(.A (fourteen_seg_o[2]), .B1 (n_38), .B2 (n_27),
       .ZN (fourteen_seg_o[8]));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[5] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [5]), .Q
       (cdc_out[5]), .QN (UNCONNECTED23));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[6] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [6]), .Q
       (cdc_out[6]), .QN (n_2));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[7] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [7]), .Q
       (cdc_out[7]), .QN (n_0));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[4] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [4]), .Q
       (cdc_out[4]), .QN (UNCONNECTED24));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[3] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [3]), .Q
       (cdc_out[3]), .QN (UNCONNECTED25));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[2] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [2]), .Q
       (cdc_out[2]), .QN (UNCONNECTED26));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[1] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [1]), .Q
       (cdc_out[1]), .QN (UNCONNECTED27));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_2_reg[0] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_slow_1 [0]), .Q
       (cdc_out[0]), .QN (UNCONNECTED28));
  NOR2_X1 g548__6131(.A1 (n_31), .A2 (n_27), .ZN (fourteen_seg_o[9]));
  OAI21_X1 g549__1881(.A (n_30), .B1 (n_38), .B2
       (i_seg_display_current_state[0]), .ZN (fourteen_seg_o[11]));
  NAND2_X1 g550__5115(.A1 (n_32), .A2 (n_27), .ZN (fourteen_seg_o[2]));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[4] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [4]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [4]), .QN (UNCONNECTED29));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[6] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [6]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [6]), .QN (UNCONNECTED30));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[2] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [2]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [2]), .QN (UNCONNECTED31));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[0] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [0]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [0]), .QN (UNCONNECTED32));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[1] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [1]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [1]), .QN (UNCONNECTED33));
  INV_X1 g556(.A (n_31), .ZN (n_32));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[3] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [3]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [3]), .QN (UNCONNECTED34));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[5] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [5]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [5]), .QN (UNCONNECTED35));
  DFFR_X1 \gen_cdc.i_cdc_register_slow_1_reg[7] (.RN (rst_ni), .CK
       (clock_slow), .D (\gen_cdc.i_cdc_register_fast [7]), .Q
       (\gen_cdc.i_cdc_register_slow_1 [7]), .QN (UNCONNECTED36));
  AND2_X1 g560__7482(.A1 (n_30), .A2 (i_seg_display_current_state[0]),
       .ZN (fourteen_seg_o[4]));
  OR2_X1 g561__4733(.A1 (i_seg_display_n_751), .A2
       (i_seg_display_current_state[0]), .ZN (n_37));
  NOR2_X1 g562__6161(.A1 (n_1), .A2 (fourteen_seg_o[5]), .ZN (n_31));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[0] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[0]), .Q
       (\gen_cdc.i_cdc_register_fast [0]), .QN (UNCONNECTED37));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[1] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[1]), .Q
       (\gen_cdc.i_cdc_register_fast [1]), .QN (UNCONNECTED38));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[3] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[3]), .Q
       (\gen_cdc.i_cdc_register_fast [3]), .QN (UNCONNECTED39));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[4] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[4]), .Q
       (\gen_cdc.i_cdc_register_fast [4]), .QN (UNCONNECTED40));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[5] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[5]), .Q
       (\gen_cdc.i_cdc_register_fast [5]), .QN (UNCONNECTED41));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[2] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[2]), .Q
       (\gen_cdc.i_cdc_register_fast [2]), .QN (UNCONNECTED42));
  INV_X1 g569(.A (i_seg_display_n_751), .ZN (n_1));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[6] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[6]), .Q
       (\gen_cdc.i_cdc_register_fast [6]), .QN (UNCONNECTED43));
  DFFR_X1 \gen_cdc.i_cdc_register_fast_reg[7] (.RN (rst_ni), .CK
       (clock_fast), .D (avg_out[7]), .Q
       (\gen_cdc.i_cdc_register_fast [7]), .QN (UNCONNECTED44));
  NAND2_X1 g572__9315(.A1 (i_seg_display_current_state[2]), .A2
       (i_seg_display_current_state[1]), .ZN (n_30));
  NOR2_X1 g573__9945(.A1 (n_28), .A2 (i_seg_display_current_state[1]),
       .ZN (fourteen_seg_o[5]));
  NAND2_X1 g574__2883(.A1 (n_28), .A2 (i_seg_display_current_state[1]),
       .ZN (i_seg_display_n_751));
  OR2_X1 g575__2346(.A1 (i_seg_display_current_state[2]), .A2
       (i_seg_display_current_state[1]), .ZN (n_38));
  DFFR_X1 \i_seg_display_current_state_reg[0] (.RN (rst_ni), .CK
       (clock_slow), .D (n_26), .Q (i_seg_display_current_state[0]),
       .QN (n_27));
  DFFR_X1 \i_seg_display_current_state_reg[1] (.RN (rst_ni), .CK
       (clock_slow), .D (n_25), .Q (i_seg_display_current_state[1]),
       .QN (UNCONNECTED45));
  AOI21_X1 g742__1666(.A (n_17), .B1 (n_23), .B2 (n_5), .ZN (n_26));
  INV_X1 g743(.A (n_24), .ZN (n_25));
  OAI22_X1 g744__7410(.A1 (n_22), .A2 (n_20), .B1 (n_17), .B2 (n_14),
       .ZN (n_24));
  DFFR_X1 \i_seg_display_current_state_reg[2] (.RN (rst_ni), .CK
       (clock_slow), .D (n_21), .Q (i_seg_display_current_state[2]),
       .QN (n_28));
  INV_X1 g746(.A (n_22), .ZN (n_23));
  OAI21_X1 g747__6417(.A (n_38), .B1 (n_37), .B2 (n_19), .ZN (n_22));
  OAI22_X1 g748__5477(.A1 (n_5), .A2 (n_16), .B1 (n_37), .B2 (n_18),
       .ZN (n_21));
  NOR2_X1 g749__2398(.A1 (n_5), .A2 (n_15), .ZN (n_20));
  INV_X1 g750(.A (n_18), .ZN (n_19));
  OAI21_X1 g751__5107(.A (cdc_out[7]), .B1 (n_13), .B2 (n_2), .ZN
       (n_18));
  AOI21_X1 g752__6260(.A (n_0), .B1 (n_12), .B2 (cdc_out[6]), .ZN
       (n_17));
  INV_X1 g753(.A (n_15), .ZN (n_16));
  AOI211_X1 g754__4319(.A (cdc_out[7]), .B (n_6), .C1 (n_7), .C2 (n_2),
       .ZN (n_15));
  AOI21_X1 g755__8428(.A (cdc_out[7]), .B1 (n_9), .B2 (n_6), .ZN
       (n_14));
  AOI21_X1 g756__5526(.A (cdc_out[5]), .B1 (n_11), .B2 (cdc_out[4]),
       .ZN (n_13));
  NOR2_X1 g757__6783(.A1 (n_8), .A2 (n_4), .ZN (n_12));
  INV_X1 g758(.A (n_10), .ZN (n_11));
  AOI211_X1 g759__3680(.A (cdc_out[2]), .B (cdc_out[3]), .C1
       (cdc_out[1]), .C2 (cdc_out[0]), .ZN (n_10));
  NAND4_X1 g760__1617(.A1 (cdc_out[5]), .A2 (cdc_out[1]), .A3
       (cdc_out[3]), .A4 (cdc_out[2]), .ZN (n_9));
  NOR3_X1 g761__2802(.A1 (n_3), .A2 (cdc_out[2]), .A3 (cdc_out[3]), .ZN
       (n_8));
  NAND3_X1 g762__1705(.A1 (n_3), .A2 (cdc_out[3]), .A3 (cdc_out[2]),
       .ZN (n_7));
  AND2_X1 g763__5122(.A1 (n_4), .A2 (n_2), .ZN (n_6));
  NAND2_X1 g764__8246(.A1 (n_1), .A2 (i_seg_display_current_state[0]),
       .ZN (n_5));
  NAND2_X1 g765__7098(.A1 (cdc_out[5]), .A2 (cdc_out[4]), .ZN (n_4));
  OR2_X1 g766__6131(.A1 (cdc_out[1]), .A2 (cdc_out[0]), .ZN (n_3));
endmodule

// GENUS UID d37fa0eb34ee6115b71f12b7fe0b461f
