
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Jun  8 2025 13:46:00 CEST (Jun  8 2025 11:46:00 UTC)

// Verification Directory fv/pipeline 

module pipeline(rst_ni, clock_slow, clock_fast, temperature,
     fourteen_seg_o);
  input rst_ni, clock_slow, clock_fast;
  input [7:0] temperature;
  output [14:0] fourteen_seg_o;
  wire rst_ni, clock_slow, clock_fast;
  wire [7:0] temperature;
  wire [14:0] fourteen_seg_o;
  wire [31:0] i_seg_display_current_state;
  wire [7:0] avg_out;
  wire [7:0] avg_measurement_previous;
  wire [7:0] avg_measurement_pre_previous;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, avg_csa_tree_ADD_TC_OP_1_groupi_n_0,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_1,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_2,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_3,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_4,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_5,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_6;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_7,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_8,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_9,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_10,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_11,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_12,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_13,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_14;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_15,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_16,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_17,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_18,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_19,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_20,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_21,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_22;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_23,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_24,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_25,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_26,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_27,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_29,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_30,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_31;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_32,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_33,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_34,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_35,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_36,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_37,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_38,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_39;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_40,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_41,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_42,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_43,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_45,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_46,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_47,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_48;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_49,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_50,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_51,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_52,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_53,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_55,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_56,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_57;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_59,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_60,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_61,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_62,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_63,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_64,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_65,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_66;
  wire avg_csa_tree_ADD_TC_OP_1_groupi_n_67,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_69,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_70,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_71,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_72,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_74,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_76,
       avg_csa_tree_ADD_TC_OP_1_groupi_n_78;
  wire avg_n_33, avg_n_34, avg_n_35, avg_n_36, avg_n_37, avg_n_38,
       avg_n_145, avg_n_146;
  wire avg_n_147, avg_n_148, i_seg_display_n_751, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_172, n_177, n_178, n_196, n_197;
  assign fourteen_seg_o[1] = 1'b0;
  assign fourteen_seg_o[3] = fourteen_seg_o[11];
  assign fourteen_seg_o[7] = 1'b0;
  assign fourteen_seg_o[10] = 1'b1;
  assign fourteen_seg_o[12] = 1'b1;
  assign fourteen_seg_o[13] = 1'b0;
  assign fourteen_seg_o[14] = 1'b0;
  INV_X1 g176437(.A (fourteen_seg_o[9]), .ZN (fourteen_seg_o[0]));
  INV_X1 g176436(.A (fourteen_seg_o[8]), .ZN (fourteen_seg_o[6]));
  OAI21_X1 g176544__2398(.A (fourteen_seg_o[2]), .B1 (n_178), .B2
       (n_168), .ZN (fourteen_seg_o[8]));
  NOR2_X1 g176545__5107(.A1 (n_172), .A2 (n_168), .ZN
       (fourteen_seg_o[9]));
  OAI21_X1 g176546__6260(.A (n_170), .B1 (n_178), .B2
       (i_seg_display_current_state[0]), .ZN (fourteen_seg_o[11]));
  OR2_X1 g176547__4319(.A1 (n_172), .A2
       (i_seg_display_current_state[0]), .ZN (fourteen_seg_o[2]));
  AND2_X1 g176548__8428(.A1 (n_170), .A2
       (i_seg_display_current_state[0]), .ZN (fourteen_seg_o[4]));
  OR2_X1 g176549__5526(.A1 (i_seg_display_n_751), .A2
       (i_seg_display_current_state[0]), .ZN (n_177));
  NOR2_X1 g176550__6783(.A1 (n_142), .A2 (fourteen_seg_o[5]), .ZN
       (n_172));
  INV_X1 g176551(.A (i_seg_display_n_751), .ZN (n_142));
  NOR2_X1 g176552__3680(.A1 (n_169), .A2
       (i_seg_display_current_state[1]), .ZN (fourteen_seg_o[5]));
  NAND2_X1 g176553__1617(.A1 (n_169), .A2
       (i_seg_display_current_state[1]), .ZN (i_seg_display_n_751));
  NAND2_X1 g176554__2802(.A1 (i_seg_display_current_state[2]), .A2
       (i_seg_display_current_state[1]), .ZN (n_170));
  OR2_X1 g176555__1705(.A1 (i_seg_display_current_state[2]), .A2
       (i_seg_display_current_state[1]), .ZN (n_178));
  DFFR_X1 \i_seg_display_current_state_reg[0] (.RN (rst_ni), .CK
       (clock_slow), .D (n_167), .Q (i_seg_display_current_state[0]),
       .QN (n_168));
  DFFR_X1 \i_seg_display_current_state_reg[1] (.RN (rst_ni), .CK
       (clock_slow), .D (n_166), .Q (i_seg_display_current_state[1]),
       .QN (UNCONNECTED));
  AOI21_X1 g176738__5122(.A (n_158), .B1 (n_164), .B2 (n_146), .ZN
       (n_167));
  INV_X1 g176739(.A (n_165), .ZN (n_166));
  OAI22_X1 g176740__8246(.A1 (n_163), .A2 (n_161), .B1 (n_158), .B2
       (n_155), .ZN (n_165));
  DFFR_X1 \i_seg_display_current_state_reg[2] (.RN (rst_ni), .CK
       (clock_slow), .D (n_162), .Q (i_seg_display_current_state[2]),
       .QN (n_169));
  INV_X1 g176742(.A (n_163), .ZN (n_164));
  OAI21_X1 g176743__7098(.A (n_178), .B1 (n_177), .B2 (n_160), .ZN
       (n_163));
  OAI22_X1 g176744__6131(.A1 (n_146), .A2 (n_157), .B1 (n_177), .B2
       (n_159), .ZN (n_162));
  NOR2_X1 g176745__1881(.A1 (n_146), .A2 (n_156), .ZN (n_161));
  INV_X1 g176746(.A (n_159), .ZN (n_160));
  OAI21_X1 g176747__5115(.A (avg_out[7]), .B1 (n_154), .B2 (n_143), .ZN
       (n_159));
  AOI21_X1 g176748__7482(.A (n_141), .B1 (n_153), .B2 (avg_out[6]), .ZN
       (n_158));
  INV_X1 g176749(.A (n_156), .ZN (n_157));
  AOI211_X1 g176750__4733(.A (avg_out[7]), .B (n_147), .C1 (n_148), .C2
       (n_143), .ZN (n_156));
  AOI21_X1 g176751__6161(.A (avg_out[7]), .B1 (n_150), .B2 (n_147), .ZN
       (n_155));
  AOI21_X1 g176752__9315(.A (avg_out[5]), .B1 (n_152), .B2
       (avg_out[4]), .ZN (n_154));
  NOR2_X1 g176753__9945(.A1 (n_149), .A2 (n_145), .ZN (n_153));
  INV_X1 g176754(.A (n_151), .ZN (n_152));
  AOI211_X1 g176755__2883(.A (avg_out[3]), .B (avg_out[2]), .C1
       (avg_out[1]), .C2 (avg_out[0]), .ZN (n_151));
  NAND4_X1 g176756__2346(.A1 (avg_out[2]), .A2 (avg_out[5]), .A3
       (avg_out[3]), .A4 (avg_out[1]), .ZN (n_150));
  NOR3_X1 g176757__1666(.A1 (n_144), .A2 (avg_out[3]), .A3
       (avg_out[2]), .ZN (n_149));
  NAND3_X1 g176758__7410(.A1 (n_144), .A2 (avg_out[3]), .A3
       (avg_out[2]), .ZN (n_148));
  AND2_X1 g176759__6417(.A1 (n_145), .A2 (n_143), .ZN (n_147));
  NAND2_X1 g176760__5477(.A1 (n_142), .A2
       (i_seg_display_current_state[0]), .ZN (n_146));
  NAND2_X1 g176761__2398(.A1 (avg_out[5]), .A2 (avg_out[4]), .ZN
       (n_145));
  OR2_X1 g176762__5107(.A1 (avg_out[1]), .A2 (avg_out[0]), .ZN (n_144));
  INV_X1 g176763(.A (avg_out[6]), .ZN (n_143));
  INV_X1 g176765(.A (avg_out[7]), .ZN (n_141));
  DFFRS_X1 \avg_data_o_reg[0] (.RN (n_25), .SN (n_35), .CK
       (clock_fast), .D (n_136), .Q (avg_out[0]), .QN (UNCONNECTED0));
  DFFRS_X1 \avg_data_o_reg[1] (.RN (n_24), .SN (n_39), .CK
       (clock_fast), .D (n_140), .Q (avg_out[1]), .QN (UNCONNECTED1));
  DFFRS_X1 \avg_data_o_reg[2] (.RN (n_28), .SN (n_34), .CK
       (clock_fast), .D (n_138), .Q (avg_out[2]), .QN (UNCONNECTED2));
  DFFRS_X1 \avg_data_o_reg[3] (.RN (n_21), .SN (n_37), .CK
       (clock_fast), .D (n_137), .Q (avg_out[3]), .QN (UNCONNECTED3));
  DFFRS_X1 \avg_data_o_reg[4] (.RN (n_27), .SN (n_36), .CK
       (clock_fast), .D (n_120), .Q (avg_out[4]), .QN (UNCONNECTED4));
  DFFRS_X1 \avg_data_o_reg[5] (.RN (n_42), .SN (n_41), .CK
       (clock_fast), .D (n_129), .Q (avg_out[5]), .QN (UNCONNECTED5));
  DFFRS_X1 \avg_data_o_reg[6] (.RN (n_26), .SN (n_40), .CK
       (clock_fast), .D (n_119), .Q (avg_out[6]), .QN (UNCONNECTED6));
  DFFRS_X1 \avg_data_o_reg[7] (.RN (n_29), .SN (n_38), .CK
       (clock_fast), .D (n_196), .Q (avg_out[7]), .QN (UNCONNECTED7));
  DFFRS_X1 \avg_measurement_pre_previous_reg[0] (.RN (n_25), .SN
       (n_35), .CK (clock_fast), .D (avg_measurement_previous[0]), .Q
       (avg_measurement_pre_previous[0]), .QN (UNCONNECTED8));
  DFFRS_X1 \avg_measurement_pre_previous_reg[1] (.RN (n_24), .SN
       (n_39), .CK (clock_fast), .D (avg_measurement_previous[1]), .Q
       (avg_measurement_pre_previous[1]), .QN (UNCONNECTED9));
  DFFRS_X1 \avg_measurement_pre_previous_reg[2] (.RN (n_28), .SN
       (n_34), .CK (clock_fast), .D (avg_measurement_previous[2]), .Q
       (avg_measurement_pre_previous[2]), .QN (UNCONNECTED10));
  DFFRS_X1 \avg_measurement_pre_previous_reg[3] (.RN (n_21), .SN
       (n_37), .CK (clock_fast), .D (avg_measurement_previous[3]), .Q
       (avg_measurement_pre_previous[3]), .QN (UNCONNECTED11));
  DFFRS_X1 \avg_measurement_pre_previous_reg[4] (.RN (n_27), .SN
       (n_36), .CK (clock_fast), .D (avg_measurement_previous[4]), .Q
       (avg_measurement_pre_previous[4]), .QN (UNCONNECTED12));
  DFFRS_X1 \avg_measurement_pre_previous_reg[5] (.RN (n_42), .SN
       (n_41), .CK (clock_fast), .D (avg_measurement_previous[5]), .Q
       (avg_measurement_pre_previous[5]), .QN (UNCONNECTED13));
  DFFRS_X1 \avg_measurement_pre_previous_reg[6] (.RN (n_26), .SN
       (n_40), .CK (clock_fast), .D (avg_measurement_previous[6]), .Q
       (avg_measurement_pre_previous[6]), .QN (UNCONNECTED14));
  DFFRS_X1 \avg_measurement_pre_previous_reg[7] (.RN (n_29), .SN
       (n_38), .CK (clock_fast), .D (avg_measurement_previous[7]), .Q
       (avg_measurement_pre_previous[7]), .QN (UNCONNECTED15));
  DFFRS_X1 \avg_measurement_previous_reg[0] (.RN (n_25), .SN (n_35),
       .CK (clock_fast), .D (temperature[0]), .Q
       (avg_measurement_previous[0]), .QN (UNCONNECTED16));
  DFFRS_X1 \avg_measurement_previous_reg[1] (.RN (n_24), .SN (n_39),
       .CK (clock_fast), .D (temperature[1]), .Q
       (avg_measurement_previous[1]), .QN (UNCONNECTED17));
  DFFRS_X1 \avg_measurement_previous_reg[2] (.RN (n_28), .SN (n_34),
       .CK (clock_fast), .D (temperature[2]), .Q
       (avg_measurement_previous[2]), .QN (UNCONNECTED18));
  DFFRS_X1 \avg_measurement_previous_reg[3] (.RN (n_21), .SN (n_37),
       .CK (clock_fast), .D (temperature[3]), .Q
       (avg_measurement_previous[3]), .QN (UNCONNECTED19));
  DFFRS_X1 \avg_measurement_previous_reg[4] (.RN (n_27), .SN (n_36),
       .CK (clock_fast), .D (temperature[4]), .Q
       (avg_measurement_previous[4]), .QN (UNCONNECTED20));
  DFFRS_X1 \avg_measurement_previous_reg[5] (.RN (n_42), .SN (n_41),
       .CK (clock_fast), .D (temperature[5]), .Q
       (avg_measurement_previous[5]), .QN (UNCONNECTED21));
  DFFRS_X1 \avg_measurement_previous_reg[6] (.RN (n_26), .SN (n_40),
       .CK (clock_fast), .D (temperature[6]), .Q
       (avg_measurement_previous[6]), .QN (UNCONNECTED22));
  DFFRS_X1 \avg_measurement_previous_reg[7] (.RN (n_29), .SN (n_38),
       .CK (clock_fast), .D (temperature[7]), .Q
       (avg_measurement_previous[7]), .QN (UNCONNECTED23));
  OAI221_X1 g177894__6260(.A (n_139), .B1 (n_131), .B2 (avg_n_38), .C1
       (n_106), .C2 (n_61), .ZN (n_140));
  AOI221_X1 g177896__4319(.A (n_133), .B1 (n_111), .B2 (avg_n_33), .C1
       (n_135), .C2 (n_22), .ZN (n_139));
  OAI21_X1 g177899__8428(.A (n_128), .B1 (n_134), .B2 (n_60), .ZN
       (n_138));
  NAND3_X1 g177900__5526(.A1 (n_127), .A2 (n_126), .A3 (n_97), .ZN
       (n_137));
  OAI211_X1 g177901__6783(.A (n_132), .B (n_125), .C1 (n_116), .C2
       (n_65), .ZN (n_136));
  OAI22_X1 g177902__3680(.A1 (n_124), .A2 (n_6), .B1 (n_116), .B2
       (avg_n_38), .ZN (n_135));
  AOI21_X1 g177905__1617(.A (n_115), .B1 (n_123), .B2 (avg_n_146), .ZN
       (n_134));
  AOI211_X1 g177906__2802(.A (n_57), .B (n_112), .C1 (n_121), .C2
       (n_11), .ZN (n_133));
  AOI22_X1 g177907__1705(.A1 (n_117), .A2 (n_64), .B1 (n_118), .B2
       (n_45), .ZN (n_132));
  AOI222_X1 g177908__5122(.A1 (n_117), .A2 (n_2), .B1 (n_74), .B2
       (n_66), .C1 (n_75), .C2 (n_68), .ZN (n_131));
  OAI221_X1 g177912__7098(.A (n_113), .B1 (n_71), .B2 (n_84), .C1
       (n_59), .C2 (n_91), .ZN (n_129));
  NAND3_X1 g177913__6131(.A1 (n_118), .A2 (avg_n_38), .A3 (n_11), .ZN
       (n_128));
  AOI22_X1 g177914__1881(.A1 (n_108), .A2 (avg_n_145), .B1 (n_74), .B2
       (n_95), .ZN (n_127));
  OAI21_X1 g177915__5115(.A (n_96), .B1 (n_109), .B2 (n_20), .ZN
       (n_126));
  NAND3_X1 g177916__7482(.A1 (n_114), .A2 (n_44), .A3 (avg_n_148), .ZN
       (n_125));
  AOI21_X1 g177917__4733(.A (n_98), .B1 (n_103), .B2 (avg_n_146), .ZN
       (n_124));
  INV_X1 g177918(.A (n_122), .ZN (n_123));
  AOI221_X1 g177919__6161(.A (n_85), .B1 (n_89), .B2 (n_47), .C1
       (n_87), .C2 (n_20), .ZN (n_122));
  NAND2_X1 g177920__9315(.A1 (n_104), .A2 (avg_n_38), .ZN (n_121));
  OAI33_X1 g177921__9945(.A1 (n_100), .A2 (n_74), .A3 (n_81), .B1
       (n_73), .B2 (n_6), .B3 (n_69), .ZN (n_120));
  OAI222_X1 g177922__2883(.A1 (n_71), .A2 (n_82), .B1 (n_90), .B2
       (n_31), .C1 (n_59), .C2 (avg_n_38), .ZN (n_119));
  INV_X1 g177923(.A (n_116), .ZN (n_115));
  OAI221_X1 g177924__2346(.A (n_99), .B1 (n_73), .B2 (n_13), .C1
       (n_75), .C2 (n_15), .ZN (n_114));
  AOI221_X1 g177925__1666(.A (n_92), .B1 (n_90), .B2 (n_30), .C1
       (n_80), .C2 (n_6), .ZN (n_113));
  OAI22_X1 g177926__7410(.A1 (n_93), .A2 (n_101), .B1 (n_86), .B2
       (n_15), .ZN (n_118));
  OAI22_X1 g177927__6417(.A1 (n_94), .A2 (n_102), .B1 (n_86), .B2
       (n_12), .ZN (n_117));
  AOI21_X1 g177928__5477(.A (n_105), .B1 (n_87), .B2 (n_53), .ZN
       (n_116));
  AOI21_X1 g177929__2398(.A (n_11), .B1 (n_87), .B2 (n_0), .ZN (n_112));
  OAI22_X1 g177930__5107(.A1 (n_86), .A2 (n_67), .B1 (n_73), .B2
       (n_61), .ZN (n_111));
  AOI221_X1 g177932__4319(.A (avg_n_33), .B1 (n_57), .B2 (avg_n_145),
       .C1 (n_88), .C2 (n_6), .ZN (n_109));
  INV_X1 g177933(.A (n_107), .ZN (n_108));
  AOI22_X1 g177934__8428(.A1 (n_87), .A2 (n_6), .B1 (n_76), .B2 (n_20),
       .ZN (n_107));
  AOI22_X1 g177935__5526(.A1 (n_87), .A2 (n_12), .B1 (n_77), .B2
       (n_14), .ZN (n_106));
  AOI22_X1 g177936__6783(.A1 (n_88), .A2 (n_12), .B1 (n_73), .B2
       (n_15), .ZN (n_105));
  NOR2_X1 g177937__3680(.A1 (n_93), .A2 (n_101), .ZN (n_104));
  NOR2_X1 g177938__1617(.A1 (n_94), .A2 (n_102), .ZN (n_103));
  NOR2_X1 g177939__2802(.A1 (n_89), .A2 (n_14), .ZN (n_102));
  NOR2_X1 g177940__1705(.A1 (n_87), .A2 (n_20), .ZN (n_100));
  NAND2_X1 g177941__5122(.A1 (n_89), .A2 (avg_n_33), .ZN (n_99));
  NOR2_X1 g177942__8246(.A1 (n_89), .A2 (n_53), .ZN (n_101));
  NOR3_X1 g177943__7098(.A1 (n_86), .A2 (n_15), .A3 (n_10), .ZN (n_98));
  OAI211_X1 g177944__6131(.A (n_89), .B (avg_n_38), .C1 (n_9), .C2
       (n_55), .ZN (n_97));
  OAI21_X1 g177945__1881(.A (n_86), .B1 (avg_n_38), .B2 (avg_n_33), .ZN
       (n_96));
  AOI22_X1 g177946__5115(.A1 (n_79), .A2 (n_58), .B1 (n_53), .B2
       (n_55), .ZN (n_95));
  NOR3_X1 g177947__7482(.A1 (n_71), .A2 (n_70), .A3 (avg_n_35), .ZN
       (n_92));
  NOR2_X1 g177948__4733(.A1 (n_74), .A2 (n_53), .ZN (n_94));
  NOR2_X1 g177949__6161(.A1 (n_74), .A2 (n_13), .ZN (n_93));
  OAI21_X1 g177950__9315(.A (avg_n_38), .B1 (n_69), .B2 (avg_n_34), .ZN
       (n_91));
  INV_X1 g177951(.A (n_89), .ZN (n_88));
  INV_X1 g177952(.A (n_87), .ZN (n_86));
  NOR3_X1 g177953__9945(.A1 (n_78), .A2 (avg_n_38), .A3 (n_15), .ZN
       (n_85));
  AOI21_X1 g177954__2883(.A (n_56), .B1 (n_70), .B2 (avg_n_35), .ZN
       (n_84));
  AOI211_X1 g177955__2346(.A (avg_n_35), .B (n_6), .C1 (n_69), .C2
       (avg_n_34), .ZN (n_90));
  OAI222_X1 g177956__1666(.A1 (n_51), .A2 (n_19), .B1 (n_33), .B2
       (n_56), .C1 (n_31), .C2 (n_17), .ZN (n_89));
  OAI221_X1 g177957__7410(.A (n_62), .B1 (n_51), .B2 (n_17), .C1
       (n_31), .C2 (n_56), .ZN (n_87));
  INV_X1 g177958(.A (n_82), .ZN (n_83));
  AOI211_X1 g177959__6417(.A (avg_n_33), .B (n_6), .C1 (avg_n_145), .C2
       (n_10), .ZN (n_81));
  OAI221_X1 g177960__5477(.A (n_48), .B1 (n_32), .B2 (n_46), .C1
       (n_33), .C2 (avg_n_35), .ZN (n_80));
  OAI21_X1 g177961__2398(.A (avg_n_38), .B1 (n_52), .B2 (avg_n_33), .ZN
       (n_79));
  NOR2_X1 g177962__5107(.A1 (n_46), .A2 (n_70), .ZN (n_82));
  INV_X1 g177963(.A (n_72), .ZN (n_78));
  INV_X1 g177964(.A (n_76), .ZN (n_77));
  INV_X1 g177965(.A (n_74), .ZN (n_73));
  OAI221_X1 g177966__6260(.A (n_59), .B1 (n_51), .B2 (n_16), .C1 (n_3),
       .C2 (n_19), .ZN (n_72));
  OAI222_X1 g177967__4319(.A1 (n_51), .A2 (n_18), .B1 (avg_n_37), .B2
       (n_17), .C1 (n_31), .C2 (avg_n_35), .ZN (n_76));
  AOI221_X1 g177968__8428(.A (n_63), .B1 (n_30), .B2 (n_17), .C1
       (n_50), .C2 (avg_n_35), .ZN (n_75));
  OAI222_X1 g177969__5526(.A1 (n_51), .A2 (n_56), .B1 (n_33), .B2
       (n_17), .C1 (n_31), .C2 (n_19), .ZN (n_74));
  INV_X1 g177970(.A (n_70), .ZN (n_69));
  NOR2_X1 g177971__6783(.A1 (n_54), .A2 (avg_n_145), .ZN (n_68));
  NAND2_X1 g177972__3680(.A1 (n_50), .A2 (avg_n_38), .ZN (n_71));
  NAND2_X1 g177973__1617(.A1 (n_55), .A2 (avg_n_145), .ZN (n_70));
  NAND3_X1 g177974__2802(.A1 (avg_n_38), .A2 (n_13), .A3 (avg_n_146),
       .ZN (n_67));
  OAI21_X1 g177975__1705(.A (n_54), .B1 (avg_n_145), .B2 (n_11), .ZN
       (n_66));
  AOI211_X1 g177976__5122(.A (n_10), .B (n_23), .C1 (avg_n_146), .C2
       (avg_n_148), .ZN (n_65));
  OAI21_X1 g177977__8246(.A (n_43), .B1 (n_45), .B2 (n_5), .ZN (n_64));
  INV_X1 g177991(.A (n_62), .ZN (n_63));
  INV_X1 g177992(.A (n_61), .ZN (n_60));
  INV_X1 g177993(.A (n_57), .ZN (n_58));
  INV_X1 g177994(.A (n_55), .ZN (n_54));
  INV_X1 g177995(.A (n_53), .ZN (n_52));
  INV_X1 g177996(.A (n_51), .ZN (n_50));
  OAI21_X1 g177998__7098(.A (n_30), .B1 (avg_n_35), .B2 (avg_n_34), .ZN
       (n_48));
  NOR2_X1 g177999__6131(.A1 (avg_n_38), .A2 (n_13), .ZN (n_47));
  NAND2_X1 g178002__1881(.A1 (n_32), .A2 (n_18), .ZN (n_62));
  NAND2_X1 g178004__5115(.A1 (avg_n_38), .A2 (n_23), .ZN (n_61));
  NAND2_X1 g178005__7482(.A1 (n_32), .A2 (avg_n_35), .ZN (n_59));
  NOR2_X1 g178006__4733(.A1 (n_6), .A2 (n_11), .ZN (n_57));
  NAND2_X1 g178007__6161(.A1 (n_17), .A2 (n_19), .ZN (n_56));
  NOR2_X1 g178008__9315(.A1 (n_0), .A2 (n_11), .ZN (n_55));
  NOR2_X1 g178009__9945(.A1 (n_14), .A2 (n_13), .ZN (n_53));
  NAND2_X1 g178010__2883(.A1 (n_33), .A2 (n_31), .ZN (n_51));
  INV_X1 g178011(.A (n_43), .ZN (n_44));
  INV_X1 g178012(.A (n_33), .ZN (n_32));
  INV_X1 g178013(.A (n_31), .ZN (n_30));
  NAND2_X1 g178014__2346(.A1 (avg_n_35), .A2 (avg_n_34), .ZN (n_46));
  NOR2_X1 g178015__1666(.A1 (n_2), .A2 (avg_n_147), .ZN (n_45));
  NAND2_X1 g178016__7410(.A1 (n_2), .A2 (avg_n_147), .ZN (n_43));
  OR2_X1 g178017__6417(.A1 (rst_ni), .A2 (temperature[5]), .ZN (n_42));
  NAND2_X1 g178018__5477(.A1 (n_7), .A2 (temperature[5]), .ZN (n_41));
  NAND2_X1 g178019__2398(.A1 (n_7), .A2 (temperature[6]), .ZN (n_40));
  NAND2_X1 g178020__5107(.A1 (n_7), .A2 (temperature[1]), .ZN (n_39));
  NAND2_X1 g178021__6260(.A1 (n_7), .A2 (temperature[7]), .ZN (n_38));
  NAND2_X1 g178022__4319(.A1 (n_7), .A2 (temperature[3]), .ZN (n_37));
  NAND2_X1 g178023__8428(.A1 (n_7), .A2 (temperature[4]), .ZN (n_36));
  NAND2_X1 g178024__5526(.A1 (n_7), .A2 (temperature[0]), .ZN (n_35));
  NAND2_X1 g178025__6783(.A1 (n_7), .A2 (temperature[2]), .ZN (n_34));
  NAND2_X1 g178026__3680(.A1 (n_3), .A2 (avg_n_36), .ZN (n_33));
  OR2_X1 g178027__1617(.A1 (n_3), .A2 (avg_n_36), .ZN (n_31));
  INV_X1 g178028(.A (n_23), .ZN (n_22));
  INV_X1 g178029(.A (n_19), .ZN (n_18));
  INV_X1 g178030(.A (n_17), .ZN (n_16));
  INV_X1 g178031(.A (n_15), .ZN (n_14));
  INV_X1 g178032(.A (n_13), .ZN (n_12));
  INV_X1 g178033(.A (n_11), .ZN (n_10));
  NOR2_X1 g178034__2802(.A1 (n_0), .A2 (n_8), .ZN (n_9));
  OR2_X1 g178035__1705(.A1 (rst_ni), .A2 (temperature[7]), .ZN (n_29));
  OR2_X1 g178036__5122(.A1 (rst_ni), .A2 (temperature[2]), .ZN (n_28));
  OR2_X1 g178037__8246(.A1 (rst_ni), .A2 (temperature[4]), .ZN (n_27));
  OR2_X1 g178038__7098(.A1 (rst_ni), .A2 (temperature[6]), .ZN (n_26));
  OR2_X1 g178039__6131(.A1 (rst_ni), .A2 (temperature[0]), .ZN (n_25));
  OR2_X1 g178040__1881(.A1 (rst_ni), .A2 (temperature[1]), .ZN (n_24));
  NOR2_X1 g178041__5115(.A1 (avg_n_146), .A2 (avg_n_147), .ZN (n_23));
  OR2_X1 g178042__7482(.A1 (rst_ni), .A2 (temperature[3]), .ZN (n_21));
  NOR2_X1 g178043__4733(.A1 (avg_n_38), .A2 (n_0), .ZN (n_20));
  NAND2_X1 g178044__6161(.A1 (n_1), .A2 (avg_n_34), .ZN (n_19));
  NAND2_X1 g178045__9315(.A1 (n_4), .A2 (avg_n_35), .ZN (n_17));
  NAND2_X1 g178046__9945(.A1 (n_0), .A2 (avg_n_145), .ZN (n_15));
  NOR2_X1 g178047__2883(.A1 (n_0), .A2 (avg_n_145), .ZN (n_13));
  NAND2_X1 g178048__2346(.A1 (avg_n_146), .A2 (avg_n_147), .ZN (n_11));
  INV_X1 g178049(.A (avg_n_145), .ZN (n_8));
  INV_X1 g178050(.A (rst_ni), .ZN (n_7));
  INV_X1 g178051(.A (avg_n_38), .ZN (n_6));
  INV_X1 g178052(.A (avg_n_148), .ZN (n_5));
  INV_X1 g178053(.A (avg_n_34), .ZN (n_4));
  INV_X1 g178054(.A (avg_n_37), .ZN (n_3));
  INV_X1 g178055(.A (avg_n_146), .ZN (n_2));
  INV_X1 g178056(.A (avg_n_35), .ZN (n_1));
  INV_X1 g178057(.A (avg_n_33), .ZN (n_0));
  AOI21_X2 avg_csa_tree_ADD_TC_OP_1_groupi_g446__1666(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_33), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_78), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_32), .ZN (avg_n_38));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g447__7410(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_78), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_38), .ZN (avg_n_37));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g448__6417(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_42), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_76), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_39), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_78));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g449__5477(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_76), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_49), .ZN (avg_n_36));
  AOI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g450__2398(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_63), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_74), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_67), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_76));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g451__5107(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_74), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_71), .ZN (avg_n_35));
  OAI211_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g452__6260(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_72), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_66), .C1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_65), .C2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_57), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_74));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g453__4319(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_69), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_70), .ZN (avg_n_34));
  OR3_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g454__8428(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_60), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_65), .A3
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_55), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_72));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g455__5526(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_67), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_27), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_71));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g456__6783(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_64), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_66), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_70));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g457__3680(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_57), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_60), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_55), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_69));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g458__1617(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_60), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_62), .ZN (avg_n_33));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g459__2802(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_67));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g460__1705(.A1
       (temperature[5]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_59),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_66));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g461(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_65), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_64));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g462__5122(.A1
       (temperature[5]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_59),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_65));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g463__8246(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_27), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_61), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_63));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g464__7098(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_55), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_56), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_62));
  AOI22_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g465__6131(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_52), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_4), .B1
       (avg_measurement_pre_previous[5]), .B2
       (avg_measurement_previous[5]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_61));
  AOI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g466__1881(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_47), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_51), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_45), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_60));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g467__5115(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_52), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_16), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_59));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g468__7482(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_51), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_53), .ZN (avg_n_145));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g469(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_57), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_56));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g470__4733(.A1
       (temperature[4]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_50),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_57));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g471__6161(.A1
       (temperature[4]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_50),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_55));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g472__9315(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_35), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_48), .ZN (avg_n_146));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g473__9945(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_45), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_46), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_53));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g474__2883(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_5), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_37), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_2), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_52));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g475__2346(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_43), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_36), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_40), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_51));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g476__1666(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_14), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_37), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_50));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g477__7410(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_39), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_41), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_49));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g478__6417(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_43), .B1 (temperature[2]),
       .B2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_29), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_48));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g479(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_46), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_47));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g480__5477(.A1
       (temperature[3]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_34),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_46));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g481__2398(.A1
       (temperature[3]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_34),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_45));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g482__5107(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_22), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_31), .ZN (avg_n_147));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g483__6260(.A1
       (temperature[2]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_29),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_43));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g484(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_41), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_42));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g485__4319(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_23), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_30), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_41));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g486__8428(.A1
       (temperature[2]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_29),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_40));
  AND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g487__5526(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_23), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_30), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_39));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g488__6783(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_32), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_20), .B2
       (avg_measurement_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_38));
  AOI22_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g489__3680(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_21), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_1), .B1
       (avg_measurement_pre_previous[3]), .B2
       (avg_measurement_previous[3]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_37));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g490(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_35), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_36));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g491__1617(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_24), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_22), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_26), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_35));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g492__2802(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_13), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_21), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_34));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g493__1705(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_20), .A2
       (avg_measurement_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_33));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g494__5122(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_20), .A2
       (avg_measurement_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_32));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g495__8246(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_26), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_25), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_31));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g496__7098(.A
       (temperature[7]), .B (avg_csa_tree_ADD_TC_OP_1_groupi_n_18), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_30));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g497__6131(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_15), .B
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_29));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g498__1881(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_12), .B
       (avg_measurement_pre_previous[0]), .ZN (avg_n_148));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g499__5115(.A
       (temperature[6]), .B (avg_csa_tree_ADD_TC_OP_1_groupi_n_17), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_27));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g500__7482(.A1
       (temperature[1]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_19),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_26));
  INV_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g501(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_24), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_25));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g502__4733(.A1
       (temperature[1]), .A2 (avg_csa_tree_ADD_TC_OP_1_groupi_n_19),
       .ZN (avg_csa_tree_ADD_TC_OP_1_groupi_n_24));
  AOI22_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g503__6161(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_10), .A2
       (avg_measurement_previous[6]), .B1 (temperature[6]), .B2
       (avg_measurement_pre_previous[6]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_23));
  AOI22_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g504__9315(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_9), .A2
       (avg_measurement_previous[0]), .B1 (temperature[0]), .B2
       (avg_measurement_pre_previous[0]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_22));
  OAI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g505__9945(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_0), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_6), .B2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_21));
  AOI21_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g506__2883(.A
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_3), .B1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_7), .B2
       (avg_measurement_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_20));
  AND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g507__2346(.A1
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_8), .A2
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_11), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_19));
  XOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g508__1666(.A
       (avg_measurement_previous[7]), .B
       (avg_measurement_pre_previous[7]), .Z
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_18));
  XOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g509__7410(.A
       (avg_measurement_previous[6]), .B
       (avg_measurement_pre_previous[6]), .Z
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_17));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g510__6417(.A
       (avg_measurement_previous[5]), .B
       (avg_measurement_pre_previous[5]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_16));
  XOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g511__5477(.A
       (avg_measurement_previous[2]), .B
       (avg_measurement_pre_previous[2]), .Z
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_15));
  XOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g512__2398(.A
       (avg_measurement_previous[4]), .B
       (avg_measurement_pre_previous[4]), .Z
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_14));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g513__5107(.A
       (avg_measurement_previous[3]), .B
       (avg_measurement_pre_previous[3]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_13));
  XNOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g514__6260(.A
       (temperature[0]), .B (avg_measurement_previous[0]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_12));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g515__4319(.A1
       (temperature[6]), .A2 (avg_measurement_pre_previous[6]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_10));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g516__8428(.A1
       (temperature[0]), .A2 (avg_measurement_pre_previous[0]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_9));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g517__5526(.A1
       (avg_measurement_previous[1]), .A2
       (avg_measurement_pre_previous[1]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_8));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g518__6783(.A1
       (temperature[7]), .A2 (avg_measurement_pre_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_7));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g519__3680(.A1
       (avg_measurement_previous[2]), .A2
       (avg_measurement_pre_previous[2]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_6));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g520__1617(.A1
       (avg_measurement_previous[1]), .A2
       (avg_measurement_pre_previous[1]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_11));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g521__2802(.A1
       (avg_measurement_previous[4]), .A2
       (avg_measurement_pre_previous[4]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_5));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g522__1705(.A1
       (avg_measurement_previous[5]), .A2
       (avg_measurement_pre_previous[5]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_4));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g523__5122(.A1
       (temperature[7]), .A2 (avg_measurement_pre_previous[7]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_3));
  NOR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g524__8246(.A1
       (avg_measurement_previous[4]), .A2
       (avg_measurement_pre_previous[4]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_2));
  OR2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g525__7098(.A1
       (avg_measurement_previous[3]), .A2
       (avg_measurement_pre_previous[3]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_1));
  NAND2_X1 avg_csa_tree_ADD_TC_OP_1_groupi_g526__6131(.A1
       (avg_measurement_previous[2]), .A2
       (avg_measurement_pre_previous[2]), .ZN
       (avg_csa_tree_ADD_TC_OP_1_groupi_n_0));
  NOR2_X1 g2(.A1 (n_197), .A2 (n_6), .ZN (n_196));
  NOR2_X1 g178058(.A1 (n_51), .A2 (n_83), .ZN (n_197));
endmodule

// GENUS UID d37fa0eb34ee6115b71f12b7fe0b461f
